export const services = [
  {
    name: "movistar",
    type: "telefonia",
    paymentId: "numero de celular",
    image: require("../../assets/services/movistar.png"),
  },
  {
    name: "personal",
    type: "telefonia",
    paymentId: "numero de celular",
    image: require("../../assets/services/personal.png"),
  },
  {
    name: "claro",
    type: "telefonia",
    paymentId: "numero de celular",
    image: require("../../assets/services/claro.png"),
  },
  {
    name: "tuenti",
    type: "telefonia",
    paymentId: "numero de celular",
    image: require("../../assets/services/tuenti.png"),
  },
  {
    name: "edenor",
    type: "electricidad",
    paymentId: "codigo de pago",
    image: require("../../assets/services/edenor.png"),
  },
  {
    name: "edesur",
    type: "electricidad",
    paymentId: "codigo de pago",
    image: require("../../assets/services/edesur.png"),
  },
  {
    name: "edea",
    type: "electricidad",
    paymentId: "codigo de pago",
    image: require("../../assets/services/edea.jpeg"),
  },
  {
    name: "aysa",
    type: "agua",
    paymentId: "codigo de pago",
    image: require("../../assets/services/aysa.png"),
  },
  {
    name: "aguas cordobesas",
    type: "agua",
    identificadordepago: "codigo de pago",
    image: require("../../assets/services/aguascordobesas.png"),
  },
  {
    name: "absa",
    type: "agua",
    paymentId: "codigo de pago",
    image: require("../../assets/services/absa.jpg"),
  },
  {
    name: "aguasrionegrinas",
    type: "agua",
    paymentId: "codigo de pago",
    image: require("../../assets/services/aguasrionegrinas.jpeg"),
  },
  {
    name: "metro gas",
    type: "gas",
    paymentId: "clave de pago electronico",
    image: require("../../assets/services/metrogas.png"),
  },
  {
    name: "naturgy",
    type: "gas",
    paymentId: "clave de pago electronico",
    image: require("../../assets/services/naturgy.png"),
  },
  {
    name: "gasnor",
    type: "gas",
    paymentId: "clave de pago electronico",
    image: require("../../assets/services/gasnor.png"),
  },
  {
    name: "cablevision",
    type: "cable",
    paymentId: "referencia de pago",
    image: require("../../assets/services/cablevision.png"),
  },
  {
    name: "directv",
    type: "cable",
    paymentId: "referencia de pago",
    image: require("../../assets/services/directv.jpeg"),
  },
  {
    name: "telecentro",
    type: "cable",
    paymentId: "referencia de pago",
    image: require("../../assets/services/telecentro.jpg"),
  },
  {
    name: "visa",
    type: "tarjetas",
    paymentId: "numero de tarjeta",
    image: require("../../assets/services/visa.jpeg"),
  },
  {
    name: "mastercard",
    type: "tarjetas",
    paymentId: "numero de tarjeta",
    image: require("../../assets/services/mastercard.jpg"),
  },
  {
    name: "americanexpress",
    type: "tarjetas",
    paymentId: "numero de tarjeta",
    image: require("../../assets/services/american.png"),
  },
  {
    name: "tarjeta naranja",
    type: "tarjetas",
    paymentId: "numero de tarjeta",
    image: require("../../assets/services/naranja.jpg"),
  },
  {
    name: "osde",
    type: "medicina prepaga",
    paymentId: "numero banelco",
    image: require("../../assets/services/osde.png"),
  },
  {
    name: "galeno",
    type: "medicina prepaga",
    paymentId: "numero banelco",
    image: require("../../assets/services/galeno.png"),
  },
  {
    name: "swiss medical",
    type: "medicina prepaga",
    paymentId: "numero banelco",
    image: require("../../assets/services/swissmedical.png"),
  },
  {
    name: "medicus",
    type: "medicina prepaga",
    paymentId: "numero banelco",
    image: require("../../assets/services/medicus.png"),
  },
  {
    name: "sube",
    type: "transporte",
    paymentId: "numero de trajeta",
    image: require("../../assets/services/sube.jpg"),
  },
];
