export const services = [
  {
    name: "movistar",
    type: "Phone Services",
    paymentId: "Phone Number",
    image: require("../../assets/services/movistar.png"),
  },
  {
    name: "personal",
    type: "Phone Services",
    paymentId: "Phone Number",
    image: require("../../assets/services/personal.png"),
  },
  {
    name: "claro",
    type: "Phone Services",
    paymentId: "Phone Number",
    image: require("../../assets/services/claro.png"),
  },
  {
    name: "tuenti",
    type: "Phone Services",
    paymentId: "Phone Number",
    image: require("../../assets/services/tuenti.png"),
  },
  {
    name: "edenor",
    type: "Electric Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/edenor.png"),
  },
  {
    name: "edesur",
    type: "Electric Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/edesur.png"),
  },
  {
    name: "edea",
    type: "Electric Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/edea.jpeg"),
  },
  {
    name: "aysa",
    type: "Water Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/aysa.png"),
  },
  {
    name: "aguas cordobesas",
    type: "Water Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/aguascordobesas.png"),
  },
  {
    name: "absa",
    type: "Water Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/absa.jpg"),
  },
  {
    name: "aguasrionegrinas",
    type: "Water Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/aguasrionegrinas.jpeg"),
  },
  {
    name: "metro gas",
    type: "Gas",
    paymentId: "Payment Code",
    image: require("../../assets/services/metrogas.png"),
  },
  {
    name: "naturgy",
    type: "Gas",
    paymentId: "Payment Code",
    image: require("../../assets/services/naturgy.png"),
  },
  {
    name: "gasnor",
    type: "Gas",
    paymentId: "Payment Code",
    image: require("../../assets/services/gasnor.png"),
  },
  {
    name: "cablevision",
    type: "Cable Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/cablevision.png"),
  },
  {
    name: "directv",
    type: "Cable Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/directv.jpeg"),
  },
  {
    name: "telecentro",
    type: "Cable Services",
    paymentId: "Payment Code",
    image: require("../../assets/services/telecentro.jpg"),
  },
  {
    name: "visa",
    type: "Credit Card",
    paymentId: "Card Number",
    image: require("../../assets/services/visa.jpeg"),
  },
  {
    name: "mastercard",
    type: "Credit Card",
    paymentId: "Card Number",
    image: require("../../assets/services/mastercard.jpg"),
  },
  {
    name: "americanexpress",
    type: "Credit Card",
    paymentId: "Card Number",
    image: require("../../assets/services/american.png"),
  },
  {
    name: "tarjeta naranja",
    type: "Credit Card",
    paymentId: "Card Number",
    image: require("../../assets/services/naranja.jpg"),
  },
  {
    name: "osde",
    type: "Health Services",
    paymentId: "Account Number",
    image: require("../../assets/services/osde.png"),
  },
  {
    name: "galeno",
    type: "Health Services",
    paymentId: "Account Number",
    image: require("../../assets/services/galeno.png"),
  },
  {
    name: "swiss medical",
    type: "Health Services",
    paymentId: "Account Number",
    image: require("../../assets/services/swissmedical.png"),
  },
  {
    name: "medicus",
    type: "Health Services",
    paymentId: "Account Number",
    image: require("../../assets/services/medicus.png"),
  },
  {
    name: "sube",
    type: "Transport Services",
    paymentId: "Card Number",
    image: require("../../assets/services/sube.jpg"),
  },
];
