const CREATE_USER ="CREATE USER";
const GET_USER = "GET_USER"
const GET_ACCOUNT="GET ACCOUNT"
const CREATE_ACCOUNT="CREATE ACCOUNT"




module.exports={
    CREATE_USER,
    GET_USER,
    GET_ACCOUNT,
    CREATE_ACCOUNT
}