const CREATE_USER ="CREATE USER";
const GET_USER = "GET_USER"
const GET_JWT ="GET TOKEN"
const GET_ACCOUNT="GET ACCOUNT"
const CREATE_ACCOUNT="CREATE ACCOUNT"
const UPDATE_USER ="UPDATE USER"
const GET_OPERATIONS = "GET OPERATIONS";




module.exports={
    GET_JWT,
    CREATE_USER,
    GET_USER,
    GET_ACCOUNT,
    CREATE_ACCOUNT,
    UPDATE_USER,
    GET_OPERATIONS
}